/**
 * Pure formatters for the auditor Plan membrane (groundnuty/macf#503, DR-026 G1).
 *
 * Two outputs, both deterministic (no I/O, no clock):
 *   - `buildProposalBody` — the Markdown body of ONE ratifiable proposal issue,
 *     assembled from the AGENT-AUTHORED signal content (signal text + rationales)
 *     plus the mechanical metadata (tier, route, distinct-agent corroboration,
 *     invariant touchpoints, HIGH-RISK flag).
 *   - `buildReport` — the dry-run Markdown report printed to stdout/--output: the
 *     promoted candidates (each rendered as a proposal preview) PLUS a separate,
 *     visible "HELD (N<threshold)" section. The default mode opens NOTHING; this
 *     report IS the default-mode artifact.
 *
 * Every proposal makes its non-actuation explicit: the operator ratifies; the
 * auditor never merges/applies (invariants #8 + #9).
 */
import { PROPOSAL_LABEL, type ProposalIssueInput } from './proposal-writer.js';
import type { CandidateSet, ProposalCandidate, RouteDecision } from './candidates.js';

/** Human-readable route label for the report + body. */
function routeLabel(route: RouteDecision): string {
  switch (route) {
    case 'needs-confirmation':
      return 'NEEDS-CONFIRMATION (universal/canonical — never auto-routed)';
    case 'project-draft':
      return 'project-rule draft';
    case 'review':
      return 'operator review (unrecognised tier hint)';
  }
}

/** A short, stable proposal title from the candidate. */
export function proposalTitle(c: ProposalCandidate): string {
  const flag = c.highRisk ? '[HIGH-RISK] ' : '';
  const oneLine = c.signal.replace(/\s+/g, ' ').trim();
  const truncated = oneLine.length > 90 ? `${oneLine.slice(0, 87)}…` : oneLine;
  return `auditor-proposal: ${flag}${truncated}`;
}

/** Render the invariant-touchpoints block (SURFACED — never a drop). */
function invariantBlock(c: ProposalCandidate): string[] {
  const lines: string[] = [];
  lines.push('## Subordination check (protected invariants)');
  lines.push('');
  if (c.invariantTouches.length === 0) {
    lines.push('_No protected invariant appears to be touched (heuristic match)._');
  } else {
    lines.push(
      'This candidate plausibly TOUCHES the following protected invariant(s). ' +
      'Touched ≠ rejected: `protected-invariants.md` permits the auditor to ' +
      '*propose* an operator-ratified amendment, so this is SURFACED for the ' +
      'operator to judge weaken-vs-amend — it is never auto-dropped (DR-026 G1).',
    );
    lines.push('');
    for (const t of c.invariantTouches) {
      lines.push(`- **#${t.index} ${t.title}** (matched: ${t.matchedKeywords.join(', ')})`);
    }
  }
  lines.push('');
  if (c.highRisk) {
    lines.push(
      '> **HIGH-RISK — apparent relaxation.** The candidate text reads like it ' +
      'WEAKENS a touched invariant. An invariant-weakening proposal is wrong by ' +
      'construction (reject at ratification) UNLESS it is a deliberate ' +
      'constitutional amendment — route it as one. The operator distinguishes ' +
      '(v1-manual; the automated weaken-vs-amend call is DR-026 G3).',
    );
    lines.push('');
  }
  return lines;
}

/**
 * Build the Markdown body for one ratifiable proposal issue. Pure assembly of
 * agent-authored content + mechanical metadata; no LLM judgment is encoded.
 */
export function buildProposalBody(c: ProposalCandidate): string {
  const lines: string[] = [];

  lines.push('> **Auditor proposal (DR-026 G1).** Generated by `macf propose` ' +
    'from corroborated F2 reflection signals. The auditor PROPOSES only — the ' +
    'operator ratifies. This issue is **never auto-merged or auto-applied** ' +
    '(invariants #8 auditor-never-acts + #9 operator-as-ratifier).');
  lines.push('');

  lines.push('## Proposed rule signal');
  lines.push('');
  lines.push(c.signal.trim());
  lines.push('');

  lines.push('## Tier + routing');
  lines.push('');
  lines.push(`- Proposed tier (agent hint): \`${c.proposedTier}\``);
  lines.push(`- Routing: ${routeLabel(c.route)}`);
  lines.push(`- Dedup handle: \`${c.handle}\`${c.hasKey ? ' (explicit key)' : ' (from signal text)'}`);
  lines.push('');

  lines.push('## Corroboration (GATE 1 — distinct agents)');
  lines.push('');
  lines.push(
    `- Distinct agents: **${c.distinctAgents}** ` +
    `(${c.corroboratingAgents.join(', ')})`,
  );
  lines.push(`- Raw occurrences: ${c.occurrences}`);
  lines.push(
    '- Promotability is gated on DISTINCT AGENTS, not occurrences: ' +
    'one agent reflecting N times is N=1 (reflection ≠ verification).',
  );
  lines.push('');

  lines.push('## Rationale (agent-authored)');
  lines.push('');
  if (c.rationales.length === 0) {
    lines.push('_No rationale supplied in the reflection signal(s)._');
  } else {
    for (const r of c.rationales) {
      lines.push(`- ${r.trim()}`);
    }
  }
  lines.push('');

  lines.push(...invariantBlock(c));

  lines.push('---');
  lines.push('');
  lines.push(
    '_Ratification is the operator\'s. To accept: distil into the appropriate ' +
    'rule tier via a PR (universal → upstream; project → local project rule), ' +
    'review + merge per `pr-discipline`. To reject: close with rationale. ' +
    'A touched/HIGH-RISK invariant is an operator judgment call, not an ' +
    'auto-drop (DR-026 G1; weaken-vs-amend automation is G3)._',
  );

  return lines.join('\n') + '\n';
}

/** Build the full `ProposalIssueInput` (title + body + labels) for a candidate. */
export function buildProposalIssueInput(
  repo: string,
  c: ProposalCandidate,
): ProposalIssueInput {
  const labels = [PROPOSAL_LABEL];
  if (c.route === 'needs-confirmation') labels.push('needs-confirmation');
  if (c.highRisk) labels.push('high-risk');
  return {
    repo,
    title: proposalTitle(c),
    body: buildProposalBody(c),
    labels,
  };
}

export interface ReportInput {
  readonly project: string;
  readonly repo: string;
  readonly candidates: CandidateSet;
  /** True when `--file` was set (artifacts opened); false = dry-run report. */
  readonly fileMode: boolean;
  /** Whether `protected-invariants.md` was found + parsed (surfaced if not). */
  readonly invariantsLoaded: boolean;
  /** Count of reflection records read (for the summary line). */
  readonly reflectionRecords: number;
  /** Count of malformed reflection lines skipped (surfaced). */
  readonly reflectionsSkipped: number;
  /** Number of reflection ledger files read. */
  readonly reflectionFiles: number;
}

/** Render one promoted candidate as a compact preview in the report. */
function candidatePreview(c: ProposalCandidate): string[] {
  const lines: string[] = [];
  const flag = c.highRisk ? ' **[HIGH-RISK]**' : '';
  lines.push(`### ${proposalTitle(c)}${flag}`);
  lines.push('');
  lines.push(`- Tier hint: \`${c.proposedTier}\` → ${routeLabel(c.route)}`);
  lines.push(
    `- Distinct agents: **${c.distinctAgents}** ` +
    `(${c.corroboratingAgents.join(', ')}) | occurrences: ${c.occurrences}`,
  );
  if (c.invariantTouches.length > 0) {
    const list = c.invariantTouches.map((t) => `#${t.index} ${t.title}`).join('; ');
    lines.push(`- Touches invariant(s): ${list} _(surfaced, not dropped)_`);
  } else {
    lines.push('- Touches invariant(s): none detected');
  }
  lines.push('- Signal:');
  lines.push('');
  for (const ln of c.signal.trim().split('\n')) {
    lines.push(`  > ${ln}`);
  }
  lines.push('');
  return lines;
}

/**
 * Build the dry-run Markdown report. Promoted candidates render as previews; the
 * HELD set renders in its own clearly-labelled section so a sub-threshold
 * candidate is VISIBLE, never silently dropped.
 */
export function buildReport(input: ReportInput): string {
  const { candidates } = input;
  const lines: string[] = [];

  lines.push(`# Auditor proposal report — ${input.project}`);
  lines.push('');
  lines.push(`- Repo: \`${input.repo}\``);
  lines.push(`- Min distinct agents (GATE 1 threshold): ${candidates.minAgents}`);
  lines.push(
    `- Mode: ${input.fileMode ? '**--file (artifacts opened)**' : '**dry-run (default — opens nothing)**'}`,
  );
  if (!input.invariantsLoaded) {
    lines.push(
      '- ⚠ `design/protected-invariants.md` not found — subordination-check ' +
      'surfaced no invariants (loud-but-proceeds).',
    );
  }
  lines.push(
    `- Reflection records: ${input.reflectionRecords} across ` +
    `${input.reflectionFiles} ledger file(s) ` +
    `(skipped malformed: ${input.reflectionsSkipped})`,
  );
  lines.push('');
  lines.push(
    '> The auditor PROPOSES only (DR-026 G1). Candidates below are corroborated ' +
    'across distinct agents; HELD candidates fell below the distinct-agent ' +
    'threshold. Nothing is auto-applied — the operator ratifies (invariants ' +
    '#8 + #9).',
  );
  lines.push('');

  // --- Promoted candidates ---
  lines.push('## Candidate proposals (promoted)');
  lines.push('');
  if (candidates.promoted.length === 0) {
    lines.push('_No candidate cleared the distinct-agent threshold._');
    lines.push('');
  } else {
    for (const c of candidates.promoted) {
      lines.push(...candidatePreview(c));
    }
  }

  // --- HELD section (visible, never silently dropped) ---
  lines.push(`## HELD (N < ${candidates.minAgents} distinct agents)`);
  lines.push('');
  lines.push(
    '_These signals are real but under-corroborated — held, NOT dropped. ' +
    'Reflection ≠ verification: one agent reflecting repeatedly is still N=1._',
  );
  lines.push('');
  if (candidates.held.length === 0) {
    lines.push('_None._');
    lines.push('');
  } else {
    for (const h of candidates.held) {
      const dedup = h.hasKey ? ` [key: \`${h.handle}\`]` : '';
      lines.push(
        `- (\`${h.proposedTier}\`) ${h.signal.replace(/\s+/g, ' ').trim()}${dedup} ` +
        `— ${h.distinctAgents} distinct agent(s), ${h.occurrences} occurrence(s)`,
      );
    }
    lines.push('');
  }

  // --- Summary ---
  lines.push('## Summary');
  lines.push('');
  lines.push(`- Promoted: ${candidates.promoted.length}`);
  lines.push(`- Held (N<${candidates.minAgents}): ${candidates.held.length}`);
  const highRisk = candidates.promoted.filter((c) => c.highRisk).length;
  const needsConfirm = candidates.promoted.filter((c) => c.route === 'needs-confirmation').length;
  lines.push(`- HIGH-RISK (apparent invariant relaxation): ${highRisk}`);
  lines.push(`- NEEDS-CONFIRMATION (universal/canonical): ${needsConfirm}`);
  lines.push('');
  lines.push(
    input.fileMode
      ? `> \`--file\` mode: ${candidates.promoted.length} ratifiable ` +
        `\`${PROPOSAL_LABEL}\` issue(s) opened (create-only; never merged/closed/edited). ` +
        'The operator ratifies.'
      : '> Dry-run: NOTHING was opened. Re-run with `--file` to open one ratifiable ' +
        `\`${PROPOSAL_LABEL}\` issue per promoted candidate (create-only).`,
  );

  return lines.join('\n').replace(/\n{3,}/g, '\n\n') + '\n';
}
